### ISSUE TITLE
Pembuatan Fitur Ketersediaan Ruangan di Rumah Sakit

### ISSUE THREAD

**Issue by bayupaoh** [JollyFrankle/jollyfrankle.github.io#1]
Halo @JollyFrankle ,
Perkenalkan saya Bayu. Kebetulan saya sering liat web kamu untuk liat info Covid-19 di NTT. Awalnya liat web nya dari postingan Pak Norman. Btw web nya sangat informatif sekali dan beta suka dengan UI web nya :)

Kebetulan saya beberapa hari ini iseng2 buat api untuk Informasi ketersedian tempat tidur di rumah sakit untuk Covid dan juga Non Covid treatment. Kira-kira bisa di webnya memungkinkan atau tidak ya untuk di tambahkan fitur **Ketersediaan Ruangan di Rumah Sakit**? Untuk datanya bisa pakai API yang saya buat hehe

Thank you

# List API
Base Url : *https://open-api-ntt.herokuapp.com/*
|No |Path   |  Method  |  Description | 
|---|---|---|---|
|1   |`api/siranap/ntt/kabupaten`   |GET   |Get list of regency in Nusa Tenggara Timur (Source: https://yankes.kemkes.go.id/app/siranap/) |
|2   |`api/siranap/ntt/tempat-tidur/covid`   |GET   |Get list of hospital bed availability for covid treatment from each hospital in Nusa Tenggara Timur (Source: https://yankes.kemkes.go.id/app/siranap/)    |
|3   |`api/siranap/ntt/tempat-tidur/covid/{id} `  |GET   |Get detail information related hospital bed availability for covid treatment (Source: https://yankes.kemkes.go.id/app/siranap/)    |
|4   |`api/siranap/ntt/tempat-tidur/non-covid `  |GET   | Get list of hospital bed availability for non covid treatment from each hospital in Nusa Tenggara Timur (Source: https://yankes.kemkes.go.id/app/siranap/   |
|5   |`api/siranap/ntt/tempat-tidur/non-covid/{id}` |GET   |Get detail information related hospital bed availability for non covid treatment (Source: https://yankes.kemkes.go.id/app/siranap/)    |

Repo : https://github.com/bayupaoh/ntt-open-api
`Note : Sangat welcome sekali kalo mau ikut contribute juga :)`

**Comment by JollyFrankle** [comment]
Terima kasih Pak @bayupaoh , nanti akan saya coba integrasikan :)

**Comment by JollyFrankle** [comment]
Pak @bayupaoh zona waktu yang digunakan UTC atau UTC+8:00 ya?

**Comment by bayupaoh** [comment]
Thanks @JollyFrankle. Kalo ada error dri API kabari aja yak di thread ini

**Comment by bayupaoh** [comment]
Itu untuk API yang mana ya @JollyFrankle ?

**Comment by JollyFrankle** [comment]
Yang tempat tidur non-COVID seperti https://open-api-ntt.herokuapp.com/api/siranap/ntt/tempat-tidur/non-covid/5306016

**Comment by bayupaoh** [comment]
Kemungkinan itu utc+8:00 sih. Kalo misal saya salah nnti saya confirm lagi yak hehehe

**Comment by JollyFrankle** [comment]
Selebihnya hingga saat ini mantap, Pak. Nanti saya coba integrasikan :)

**Comment by bayupaoh** [comment]
Sip. Thanks @JollyFrankle
